List<Map<String, String>> products = [
  {
    "name": "Shirt",
    "description": "girls shirt with floral design",
    "price" : "1200 EGP",
    "imagePath": "assets/images/shirt1.jpg",
  },
  {
    "name": "pants",
    "description": "wide Leg pants with side stripes",
    "price" : "950 EGP",
    "imagePath": "assets/images/pans1.jpg",
  },
  {
    "name": "Jacket",
    "description": "Black jacket for mens with zipper details",
    "price" : "1250 EGP",
    "imagePath": "assets/images/jacket1.jpg",
  },
  {
    "name": "Shirt",
    "description": "Cotton shirt with checkered pattern",
    "price" : "1100 EGP",
    "imagePath": "assets/images/shirt2.jpg",
  },
  {
    "name": "Shirt",
    "description": "Casual shirt",
    "price" : "850 EGP",
    "imagePath": "assets/images/image5.jpeg",
  },
  {
    "name": "Jacket",
    "description": "Denim jacket with distressed look",
    "price" : "1150 EGP",
    "imagePath": "assets/images/jacket2.jpg",
  },
  {
    "name": "pants",
    "description": "Slim-fit trousers",
    "price" : "1000 EGP",
    "imagePath": "assets/images/pans2.jpg",
  },
  {
    "name": "Shirt",
    "description": "Striped shirt",
    "price" : "950 EGP",
    "imagePath": "assets/images/shirt3.jpg",
  },
  {
    "name": "Shirt",
    "description": "Cotton shirt",
    "price" : "1200 EGP",
    "imagePath": "assets/images/shirt4.jpg",
  },
  {
    "name": "pants",
    "description": "Cargo pants with multiple pockets",
    "price" : "1150 EGP",
    "imagePath": "assets/images/pans3.jpg",
  },
  {
    "name": "pants",
    "description": "Skinny jeans",
    "price" : "1000 EGP",
    "imagePath": "assets/images/pans4.jpg",
  },
  {
    "name": "Shirt",
    "description": "Floral print shirt",
    "price" : "1200 EGP",
    "imagePath": "assets/images/shirt5.jpg",
  },
  {
    "name": "Boot",
    "description": "Leather boots",
    "price" : "1250 EGP",
    "imagePath": "assets/images/shoes1.jpg",
  },
  {
    "name": "pants",
    "description": "Chinos",
    "price" : "900 EGP",
    "imagePath": "assets/images/pans5.jpg",
  },
  {
    "name": "Shirt",
    "description": "V-neck t-shirt",
    "price" : "850 EGP",
    "imagePath": "assets/images/shirt6.jpg",
  },
  {
    "name": "pants",
    "description": "Cropped trousers",
    "price" : "1100 EGP",
    "imagePath": "assets/images/pans6.jpg",
  },
  {
    "name": "Jacket",
    "description": "Hooded jacket",
    "price" : "1280 EGP",
    "imagePath": "assets/images/jacket3.jpg",
  },
  {
    "name": "pants",
    "description": "Sweatpants",
    "price" : "920 EGP",
    "imagePath": "assets/images/pans7.jpg",
  },
  {
    "name": "Shirt",
    "description": "Long-sleeve shirt",
    "price" : "800 EGP",
    "imagePath": "assets/images/shirt7.jpg",
  },
  {
    "name": "Shirt",
    "description": "Denim shirt",
    "price" : "1150 EGP",
    "imagePath": "assets/images/shirt8.jpg",
  },
  {
    "name": "Boot",
    "description": "Suede ankle boots",
    "price" : "1250 EGP",
    "imagePath": "assets/images/shoes2.jpg",
  },
  {
    "name": "Boot",
    "description": "Leather boots",
    "price" : "1200 EGP",
    "imagePath": "assets/images/shoes3.jpg",
  },
  {
    "name": "Shirt",
    "description": "Button-up shirt",
    "price" : "950 EGP",
    "imagePath": "assets/images/shirt9.jpg",
  },
  {
    "name": "Bag",
    "description": "Canvas tote bag",
    "price" : "800 EGP",
    "imagePath": "assets/images/bag1.jpg",
  },
  {
    "name": "Jacket",
    "description": "Puffer jacket",
    "price" : "1200 EGP",
    "imagePath": "assets/images/jacket4.jpg",
  },
  {
    "name": "Bag",
    "description": "Leather shoulder bag",
    "price" : "950 EGP",
    "imagePath": "assets/images/bag2.png",
  },
  {
    "name": "Jacket",
    "description": "Bomber jacket",
    "price" : "1200 EGP",
    "imagePath": "assets/images/jacket5.jpeg",
  },
  {
    "name": "Bag",
    "description": "Crossbody bag",
    "price" : "780 EGP",
    "imagePath": "assets/images/bag3.jpeg",
  },
  {
    "name": "Bag",
    "description": "Nylon backpack",
    "price" : "950 EGP",
    "imagePath": "assets/images/bag4.jpeg",
  },
  // Add more products as needed
];

List catlist = [
  "All",
  "jackets",
  "shirts",
  "pants",
  "Bags",
];
