List<Map<String, dynamic>> products = [
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "girls shirt with floral design",
    "price": 1200,
    "image": "assets/images/shirt1.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "wide Leg pants with side stripes",
    "price": 950,
    "image": "assets/images/pans1.jpg",
  },
  {
    "id": null,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Black jacket for mens with zipper details",
    "price": 1250,
    "image": "assets/images/jacket1.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Cotton shirt with checkered pattern",
    "price": 1100,
    "image": "assets/images/shirt2.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Casual shirt",
    "price": 850,
    "image": "assets/images/image5.jpeg",
  },
  {
    "id": null,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Denim jacket with distressed look",
    "price": 1150,
    "image": "assets/images/jacket2.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Slim-fit trousers",
    "price": 1000,
    "image": "assets/images/pans2.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Striped shirt",
    "price": 950,
    "image": "assets/images/shirt3.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Cotton shirt",
    "price": 1200,
    "image": "assets/images/shirt4.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Cargo pants with multiple pockets",
    "price": 1150,
    "image": "assets/images/pans3.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Skinny jeans",
    "price": 1000,
    "image": "assets/images/pans4.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Floral print shirt",
    "price": 1200,
    "image": "assets/images/shirt5.jpg",
  },
  {
    "id": null,
    "typeID": 5,
    "name": "Boot",
    "desc": "Leather boots",
    "price": 1250,
    "image": "assets/images/shoes1.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Chinos",
    "price": 900,
    "image": "assets/images/pans5.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "V-neck t-shirt",
    "price": 850,
    "image": "assets/images/shirt6.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Cropped trousers",
    "price": 1100,
    "image": "assets/images/pans6.jpg",
  },
  {
    "id": null,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Hooded jacket",
    "price": 1280,
    "image": "assets/images/jacket3.jpg",
  },
  {
    "id": null,
    "typeID": 3,
    "name": "pants",
    "desc": "Sweatpants",
    "price": 920,
    "image": "assets/images/pans7.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Long-sleeve shirt",
    "price": 800,
    "image": "assets/images/shirt7.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Denim shirt",
    "price": 1150,
    "image": "assets/images/shirt8.jpg",
  },
  {
    "id": null,
    "typeID": 5,
    "name": "Boot",
    "desc": "Suede ankle boots",
    "price": 1250,
    "image": "assets/images/shoes2.jpg",
  },
  {
    "id": null,
    "typeID": 5,
    "name": "Boot",
    "desc": "Leather boots",
    "price": 1200,
    "image": "assets/images/shoes3.jpg",
  },
  {
    "id": null,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Button-up shirt",
    "price": 950,
    "image": "assets/images/shirt9.jpg",
  },
  {
    "id": null,
    "typeID": 4,
    "name": "Bag",
    "desc": "Canvas tote bag",
    "price": 800,
    "image": "assets/images/bag1.jpg",
  },
  {
    "id": null,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Puffer jacket",
    "price": 1200,
    "image": "assets/images/jacket4.jpg",
  },
  {
    "id": null,
    "typeID": 4,
    "name": "Bag",
    "desc": "Leather shoulder bag",
    "price": 950,
    "image": "assets/images/bag2.png",
  },
  {
    "id": null,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Bomber jacket",
    "price": 1200,
    "image": "assets/images/jacket5.jpeg",
  },
  {
    "id": null,
    "typeID": 4,
    "name": "Bag",
    "desc": "Crossbody bag",
    "price": 780,
    "image": "assets/images/bag3.jpeg",
  },
  {
    "id": null,
    "typeID": 4,
    "name": "Bag",
    "desc": "Nylon backpack",
    "price": 950,
    "image": "assets/images/bag4.jpeg",
  },
  // Add more products as needed
];

List<Map<String, dynamic>> types = [
  {
    "id": 1,
    "name": "Jacket",
  },
  {
    "id": 2,
    "name": "Shirt",
  },
  {
    "id": 3,
    "name": "pants",
  },
  {
    "id": 4,
    "name": "Bag",
  },
  {
    "id": 5,
    "name": "Boot",
  },
];

List catlist = [
  "All",
  "jackets",
  "shirts",
  "pants",
  "Bags",
];
